#pragma once

// Taken from glfw3.h
#define EC_MOUSE_BUTTON_1      0
#define EC_MOUSE_BUTTON_2      1
#define EC_MOUSE_BUTTON_3      2
#define EC_MOUSE_BUTTON_4      3
#define EC_MOUSE_BUTTON_5      4
#define EC_MOUSE_BUTTON_6      5
#define EC_MOUSE_BUTTON_7      6
#define EC_MOUSE_BUTTON_8      7
#define EC_MOUSE_BUTTON_LAST   EC_MOUSE_BUTTON_8
#define EC_MOUSE_BUTTON_LEFT   EC_MOUSE_BUTTON_1
#define EC_MOUSE_BUTTON_RIGHT  EC_MOUSE_BUTTON_2
#define EC_MOUSE_BUTTON_MIDDLE EC_MOUSE_BUTTON_3